version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./repositories:/app/repositories
      - ./data:/app/data
    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=your_secure_password
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "80:3000"

  # This is where the frontend would go
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "80:3000"
  #   depends_on:
  #     - git-service
  #   restart: unless-stopped