name: Run Tests

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build and run tests in Docker
      run: |
        cd backend
        chmod +x run-tests.sh
        # Force Docker execution by not using the --local flag
        ./run-tests.sh
        
    - name: Fallback to local tests if Docker fails
      if: failure()
      run: |
        # Install Zig and dependencies if Docker execution fails
        ZIG_VERSION=0.14.0
        wget -c https://ziglang.org/download/${ZIG_VERSION}/zig-linux-x86_64-${ZIG_VERSION}.tar.xz
        tar -xf zig-linux-x86_64-${ZIG_VERSION}.tar.xz
        echo "$(pwd)/zig-linux-x86_64-${ZIG_VERSION}" >> $GITHUB_PATH
        
        sudo apt-get update
        sudo apt-get install -y libgit2-dev libsqlite3-dev
        
        cd backend
        ./run-tests.sh --local
        
    - name: Report test results
      if: always()
      run: |
        echo "Test exit code: ${{ job.status }}"
