name: Run Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build and run tests
      run: |
        cd backend
        chmod +x run-tests.sh
        ./run-tests.sh
        
    - name: Report test results
      if: always()
      run: |
        echo "Test exit code: ${{ job.status }}"
