name: Run Tests

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Install Docker and docker-compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose
        docker --version
        docker-compose --version
        
    - name: Try Docker execution
      id: docker_test
      run: |
        cd backend
        chmod +x run-tests.sh
        ./run-tests.sh
      continue-on-error: true
        
    - name: Install Zig and dependencies (fallback)
      if: steps.docker_test.outcome == 'failure'
      run: |
        ZIG_VERSION=0.14.0
        wget -c https://ziglang.org/download/${ZIG_VERSION}/zig-linux-x86_64-${ZIG_VERSION}.tar.xz
        tar -xf zig-linux-x86_64-${ZIG_VERSION}.tar.xz
        echo "$PWD/zig-linux-x86_64-${ZIG_VERSION}" >> $GITHUB_PATH
        export PATH="$PWD/zig-linux-x86_64-${ZIG_VERSION}:$PATH"
        zig version
        
        # Install dependencies for local execution
        sudo apt-get update
        sudo apt-get install -y libgit2-dev libsqlite3-dev
        
    - name: Run tests locally (fallback)
      if: steps.docker_test.outcome == 'failure'
      run: |
        cd backend
        export PATH="$PWD/../zig-linux-x86_64-${ZIG_VERSION}:$PATH"
        chmod +x run-tests.sh
        ./run-tests.sh --local
        
    - name: Report test results
      run: |
        if [ "${{ steps.docker_test.outcome }}" == "success" ]; then
          echo "✅ Docker tests passed successfully!"
          exit 0
        elif [ "${{ steps.docker_test.outcome }}" == "failure" ] && [ "${{ job.status }}" == "success" ]; then
          echo "✅ Local tests passed successfully (Docker tests failed)!"
          exit 0
        else
          echo "❌ All tests failed!"
          exit 1
        fi
